spring.application.name=SpringWebApplication
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port=8080
# =============================
# Primary Datasource (MySQL) — Student Module
# =============================
spring.datasource.url=jdbc:mysql://localhost:3306/students
spring.datasource.username=root
spring.datasource.password=Ratanlord@1409
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# =============================
# Secondary Datasource (PostgreSQL) — Employee Module
# =============================
employee.datasource.url=jdbc:postgresql://localhost:5432/employees
employee.datasource.username=postgres
employee.datasource.password=Ratanlord@1409
employee.datasource.driver-class-name=org.postgresql.Driver

employee.jpa.hibernate.ddl-auto=update
employee.jpa.show-sql=true
employee.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# =============================
# Mock Datasource (H2) — Test Module
# =============================
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password